### ISSUE TITLE
NavX is broken in latest WPILib

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib-utilities#43]
```
04:56:36:580 WARNING : navx                : Error reading configuration data, retrying (CRC error)
04:56:37:086 WARNING : navx                : Error reading configuration data, retrying (CRC error)
04:56:37:590 WARNING : navx                : Error reading configuration data, retrying (CRC error)
04:56:38:093 WARNING : navx                : Error reading configuration data, retrying (CRC error)
04:56:38:597 WARNING : navx                : Error reading configuration data, retrying (CRC error)
04:56:39:099 WARNING : navx                : -- Did not get configuration data
04:56:39:104 ERROR   : navx                : Error getting data
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/robotpy_ext/common_drivers/navx/registerio.py", line 101, in run
    self.getCurrentData()
  File "/usr/local/lib/python3.6/site-packages/robotpy_ext/common_drivers/navx/registerio.py", line 163, in getCurrentData
    curr_data = self.io_provider.read(first_address, read_count)
  File "/usr/local/lib/python3.6/site-packages/robotpy_ext/common_drivers/navx/registerio_spi.py", line 74, in read
    raise IOError("CRC error")
OSError: CRC error


Locals at innermost frame:

{ 'count': 82,
  'crc': 255,
  'data': [ 255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
            255,
...

```

**Comment by virtuald** [comment]
I'm an idiot and didn't even have the NavX plugged in when I did the test. :(
